---
title: "International Tourism Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(janitor)
library(DT)
library(forcats)
library(highcharter)
library(scales)

df <- read_csv('data/International_Tourism_Dataset_Long.csv') %>%
  clean_names()

test <- read_csv('data/International_Tourism_Dataset_Short.csv') %>%
  filter(indicator == 'International tourism, expenditures (current US$)')
```

# Inbound Tourists 

Column {.tabset .tabset-fade datawidth=750}
------------------------------------- 

### Inbound Tourists 2020

```{r}
df %>%
  filter(
    indicator == 'International tourism, number of arrivals',
    year == 2020) %>%
  mutate(label = number(value, big.mark = ",")) %>%
  hcmap(
    map = 'custom/world-robinson-lowres',
    download_map_data = TRUE,
    value = "value",
    name = 'Number of Arriving Tourists',
    joinBy = c('iso-a3','iso3c'),
    tooltip = list(
      pointFormat = "{point.country}: {point.label}"
    )
  ) %>%
  hc_colorAxis(
    stops = color_stops(colors = viridisLite::inferno(10, begin = 0.1)),
    max = 10^8,
    labels = list(
      overflow = 'allow'
    )
  ) %>%
  hc_title(text = 'Which countries recieve the most Tourist')
```

### Inbound Tourists 2019

```{r}
df %>%
  filter(
    indicator == 'International tourism, number of arrivals',
    year == 2019) %>%
  mutate(label = number(value, big.mark = ",")) %>%
  hcmap(
    map = 'custom/world-robinson-lowres',
    download_map_data = TRUE,
    value = "value",
    name = 'Number of Arriving Tourists',
    joinBy = c('iso-a3','iso3c'),
    tooltip = list(
      pointFormat = "{point.country}: {point.label}"
    )
  ) %>%
  hc_colorAxis(
    stops = color_stops(colors = viridisLite::inferno(10, begin = 0.1)),
    max = 10^8,
    labels = list(
      overflow = 'allow'
    )
   ) %>%
   hc_title(text = 'Which countries recieve the most Tourist')

```

### Inbound Tourists 2018

```{r}
df %>%
  filter(
    indicator == 'International tourism, number of arrivals',
    year == 2018) %>%
  mutate(label = number(value, big.mark = ",")) %>%
  hcmap(
    map = 'custom/world-robinson-lowres',
    download_map_data = TRUE,
    value = "value",
    name = 'Number of Arriving Tourists',
    joinBy = c('iso-a3','iso3c'),
    tooltip = list(
      pointFormat = "{point.country}: {point.label}"
    )
  ) %>%
  hc_colorAxis(
    stops = color_stops(colors = viridisLite::inferno(10, begin = 0.1)),
    max = 10^8,
    labels = list(
      overflow = 'allow'
    )
   ) %>%
   hc_title(text = 'Which countries recieve the most Tourist')

```


Column {.tabset .tabset-fade data-width=250}
-----------------------------------------------------------------------

### 2019 Leaders

```{r}
df %>%
  filter(
    indicator == 'International tourism, number of arrivals') %>%
  group_by(country) %>%
  mutate(growth_rate = (value - lag(value)) / lag(value),
         label_gr = percent(growth_rate, accuracy = 0.01)) %>%
  mutate(prev_year_value = lag(value)) %>%
  ungroup() %>%
  filter(year == 2020) %>%
  filter(!is.na(growth_rate)) %>%
  arrange(-prev_year_value) %>%
  mutate(label_value = number(value, big.mark = ","),
         label_pyv = number(prev_year_value, big.mark = ",")) %>%
  slice_head(n= 10) %>%
  mutate(country = as_factor(country)) %>%
  hchart(
    'bar',
    hcaes(x = country,
          y = growth_rate),
    color = "#CC4248FF",
    tooltip = list(
      useHTML = TRUE,
      pointFormat = 
        "Growth Rate: {point.label}<br>2019 Tourists: {point.label_pyv}<br> 2020 Tourists: {point.label_value}"
    )
  ) %>%
  hc_xAxis(
    title = list(text = "")
  ) %>%
  hc_yAxis(
    title = list(text = "Percent Change")
  ) %>%
    hc_title(
    text = 'Percent Change - 2019 to 2020'
  )
```

### Smallest Decreases

```{r}
df %>%
  filter(
    indicator == 'International tourism, number of arrivals') %>%
  group_by(country) %>%
  mutate(growth_rate = (value - lag(value)) / lag(value),
         label_gr = percent(growth_rate, accuracy = 0.01)) %>%
  mutate(prev_year_value = lag(value)) %>%
  ungroup() %>%
  filter(year == 2020) %>%
  filter(!is.na(growth_rate)) %>%
  arrange(-growth_rate) %>%
  mutate(label_value = number(value, big.mark = ","),
         label_pyv = number(prev_year_value, big.mark = ",")) %>%
  slice_head(n= 10) %>%
  mutate(country = as_factor(country)) %>%
  hchart(
    'bar',
    hcaes(x = country,
          y = growth_rate),
    color = "#CC4248FF",
    tooltip = list(
      useHTML = TRUE,
      pointFormat = 
        "Growth Rate: {point.label}<br>2019 Tourists: {point.label_pyv}<br> 2020 Tourists: {point.label_value}"
    )
  ) %>%
  hc_xAxis(
    title = list(text = "")
  ) %>%
  hc_yAxis(
    title = list(text = "Percent Change")
  ) %>%
    hc_title(
    text = 'Percent Change - 2019 to 2020'
  )
```

### Largest Decreases

```{r}
df %>%
  filter(
    indicator == 'International tourism, number of arrivals') %>%
  group_by(country) %>%
  mutate(growth_rate = (value - lag(value)) / lag(value),
         label_gr = percent(growth_rate, accuracy = 0.01)) %>%
  mutate(prev_year_value = lag(value)) %>%
  ungroup() %>%
  filter(year == 2020) %>%
  filter(!is.na(growth_rate)) %>%
  arrange(growth_rate) %>%
  mutate(label_value = number(value, big.mark = ","),
         label_pyv = number(prev_year_value, big.mark = ",")) %>%
  slice_head(n= 10) %>%
  mutate(country = as_factor(country)) %>%
  hchart(
    'bar',
    hcaes(x = country,
          y = growth_rate),
    color = "#CC4248FF",
    tooltip = list(
      useHTML = TRUE,
      pointFormat = 
        "Growth Rate: {point.label}<br>2019 Tourists: {point.label_pyv}<br> 2020 Tourists: {point.label_value}"
    )
  ) %>%
  hc_xAxis(
    title = list(text = "")
  ) %>%
  hc_yAxis(
    title = list(text = "Percent Change")
  ) %>%
  hc_title(
    text = 'Percent Change - 2019 to 2020'
  )
```

# Outbound Tourists

Column {.tabset .tabset-fade datawidth=800}
-----------------------------------------------------------------------

### Outbound Tourists in 2020

```{r}
df %>%
  filter(
    indicator == 'International tourism, number of departures',
    year == 2020) %>%
  mutate(label = number(value, big.mark = ",")) %>%
  hcmap(
    map = 'custom/world-robinson-lowres',
    download_map_data = TRUE,
    value = "value",
    name = 'Number of Departing Tourists',
    joinBy = c('iso-a3','iso3c'),
    tooltip = list(
      pointFormat = "{point.country}: {point.label}"
    )
  ) %>%
  hc_colorAxis(
    stops = color_stops(colors = viridisLite::inferno(10, begin = 0.1)),
    max = 10^8,
    labels = list(
      overflow = 'allow'
    )
  ) %>%
  hc_title(text = 'Which countries depart the most for tourism')
```

### Outbound Tourists in 2019

```{r}
df %>%
  filter(
    indicator == 'International tourism, number of departures',
    year == 2019) %>%
  mutate(label = number(value, big.mark = ",")) %>%
  hcmap(
    map = 'custom/world-robinson-lowres',
    download_map_data = TRUE,
    value = "value",
    name = 'Number of Departing Tourists',
    joinBy = c('iso-a3','iso3c'),
    tooltip = list(
      pointFormat = "{point.country}: {point.label}"
    )
  ) %>%
  hc_colorAxis(
    stops = color_stops(colors = viridisLite::inferno(10, begin = 0.1)),
    max = 10^8,
    labels = list(
      overflow = 'allow'
    )
  ) %>%
  hc_title(text = 'Which countries depart the most for tourism')
```

### Outbound Tourists in 2018

```{r}
df %>%
  filter(
    indicator == 'International tourism, number of departures',
    year == 2018) %>%
  mutate(label = number(value, big.mark = ",")) %>%
  hcmap(
    map = 'custom/world-robinson-lowres',
    download_map_data = TRUE,
    value = "value",
    name = 'Number of Departing Tourists',
    joinBy = c('iso-a3','iso3c'),
    tooltip = list(
      pointFormat = "{point.country}: {point.label}"
    )
  ) %>%
  hc_colorAxis(
    stops = color_stops(colors = viridisLite::inferno(10, begin = 0.1)),
    max = 10^8,
    labels = list(
      overflow = 'allow'
    )
  ) %>%
  hc_title(text = 'Which countries depart the most for tourism')
```

Column {data-width=200}
-----------------------------------------------------------------------

### Chart C

```{r}

```